version: '3.8'

services:      
  bookings-api:
    build:
      context: .
      dockerfile: Bookings.Api/Dockerfile
    networks:
      - proxy
    ports:
      - 8081:80
#    depends_on:
#      - bookings-db
#      - rabbitMQ
    environment:
      Api_DB_USER: "${BOOKINGS_DB_USER}"
      Api_DB_PASSWORD: "${BOOKINGS_DB_PASSWORD}"
      Api_DB_HOST: "${MAIN_SERVER_ADDRESS}"
      Api_DB_PORT: "${BOOKINGS_DB_PORT}"
      Api_RabbitMq_Host: "${MAIN_SERVER_ADDRESS}"
      Api_RabbitMq_User: "${RABBITMQ_USER}"
      Api_RabbitMq_Password: "${RABBITMQ_PASSWORD}"
      Api_StorageEndpoint_Address: "${MAIN_SERVER_ADDRESS}:8080"
  
networks:
  proxy:
    driver: bridge