version: '3.8'

services:
  bookings-storage:
    build:
      context: .
      dockerfile: Bookings.Storage/Dockerfile
    networks:
      - proxy
    ports:
      - 8080:80
#    depends_on:
#      - bookings-db
#      - rabbitMQ
    environment:
      Bookings_Storage_DB_USER: "${BOOKINGS_DB_USER}"
      Bookings_Storage_DB_PASSWORD: "${BOOKINGS_DB_PASSWORD}"
      Bookings_Storage_DB_HOST: "${MAIN_SERVER_ADDRESS}"
      Bookings_Storage_DB_PORT: "${BOOKINGS_DB_PORT}"
      Bookings_Storage_RabbitMq_Host: "${MAIN_SERVER_ADDRESS}"
      Bookings_Storage_RabbitMq_User: "${RABBITMQ_USER}"
      Bookings_Storage_RabbitMq_Password: "${RABBITMQ_PASSWORD}"
  
networks:
  proxy:
    driver: bridge