version: '3.8'

services:
#  bookings-storage:
#    build:
#      context: .
#      dockerfile: Bookings.Storage/Dockerfile
#    networks:
#      - proxy
#    ports:
#      - 8081:80
#    depends_on:
#      - api-db
#      - api-rabbitMQ
#    environment:
#      Bookings_Storage__DB_USER: "${BOOKINGS_DB_USER}"
#      Bookings_Storage__DB_PASSWORD: "${BOOKINGS_DB_PASSWORD}"
#      Bookings_Storage__DB_HOST: "${MAIN_SERVER_ADDRESS}"
#      Bookings_Storage__DB_PORT: "${BOOKINGS_DB_PORT}"
#      Bookings_Storage__RabbitMq_Host: "${MAIN_SERVER_ADDRESS}"
#      Bookings_Storage__RabbitMq_User: "${RABBITMQ_USER}"
#      Bookings_Storage__RabbitMq_Password: "${RABBITMQ_PASSWORD}"

  bookings-db:
    restart: always
    image: mongo:6.0.7
    command: --bind_ip_all
    volumes:
        - ./data/bookings-data:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: "${BOOKINGS_DB_USER}"
        MONGO_INITDB_ROOT_PASSWORD: "${BOOKINGS_DB_PASSWORD}"
    networks:
      - proxy
    ports:
      - 27017:27017

  rabbitMQ:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    container_name: rabbitmq
    labels:
      NAME: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    networks:
      - proxy
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

volumes:
  bookings-data:
  
networks:
  proxy:
    driver: bridge